In [87]:
import numpy as np
np.set_printoptions(precision=4)

In [2]:
probs = {
         'Burger':{'Burger':0.1, 'Pizza':0.2, 'HotDog':0.7}, 
         'Pizza':{'Burger':0.8, 'HotDog':0.2}, 
         'HotDog':{'Burger':0.3, 'Pizza':0.45, 'HotDog':0.25}
        }

In [19]:
np.random.choice(list(probs['Burger'].keys()), p=list(probs['Burger'].values()))

'HotDog'

In [42]:
N = 1000000
res = []
curr_state = 'Burger'
res.append(curr_state)
for i in range(N):
    next_state = np.random.choice(list(probs[curr_state].keys()), p=list(probs[curr_state].values()))
    res.append(next_state)
    curr_state = next_state

In [43]:
res = np.array(res)
val_counts = np.unique(res, return_counts=True)
dict(zip(list(val_counts[0]), list(val_counts[1]/N)))

{'Burger': 0.353736, 'HotDog': 0.39746, 'Pizza': 0.248805}

In [ ]:
{'Burger': 0.35629, 'HotDog': 0.3964, 'Pizza': 0.24732}

In [46]:
A = [[0.1, 0.2, 0.7], [0.8, 0, 0.2], [0.3, 0.45, 0.25]]
A = np.array(A)
A

array([[0.1 , 0.2 , 0.7 ],
       [0.8 , 0.  , 0.2 ],
       [0.3 , 0.45, 0.25]])

In [88]:
e_vals, e_vecs = np.linalg.eig(A.T)
for idx in np.where(np.round(e_vals, 5) == 1)[0]:
    print(dict(zip(list(probs.keys()), (e_vecs.T[idx]/e_vecs.T[idx].sum()).real)))

{'Burger': 0.3538873994638071, 'Pizza': 0.24932975871313673, 'HotDog': 0.39678284182305595}


In [65]:
from scipy.linalg import eig

In [66]:
eig(A, left=True)

(array([ 1.   +0.j    , -0.325+0.3307j, -0.325-0.3307j]),
 array([[ 0.6026+0.j    ,  0.4743+0.4183j,  0.4743-0.4183j],
        [ 0.4246+0.j    ,  0.1581-0.4183j,  0.1581+0.4183j],
        [ 0.6757+0.j    , -0.6325+0.j    , -0.6325-0.j    ]]),
 array([[ 0.5774+0.j    , -0.2439+0.4047j, -0.2439-0.4047j],
        [ 0.5774+0.j    ,  0.7607+0.j    ,  0.7607-0.j    ],
        [ 0.5774+0.j    , -0.2604-0.3609j, -0.2604+0.3609j]]))